name: Build/Release

on:
  push:
    tags:
      - v**
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - id: checkout-git-repository
        name: Checkout Git repository
        uses: actions/checkout@v5
      - id: install-nodejs
        name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - id: install-dependencies
        name: Install dependencies
        run: npm install
      - id: lint
        name: Lint
        run: |
          npm run lint
      - id: test
        name: Test
        run: |
          npm run test
      - id: build-electron-app
        name: Build Electron app
        uses: sudovijay/action-electron-builder@v1.7.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') || contains(github.event.head_commit.message, '/release') }}
